#!/bin/bash
# Sample script to generate random numbers to terminal - "One number at a time"
# Author : Umesh Kumar Soni

shuf -i 1-10 -n 10

# shuf -> function for generating random numbers
# -i -> input range 
# 1-10 -> LOW - HIGH 
# -n -> head count 
